# Generated by Django 2.0 on 2018-08-09 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field=500, upload_to='.', width_field=500)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Upload Date')),
                ('verified', models.BooleanField(default=False)),
                ('rejected', models.NullBooleanField(default=None)),
            ],
        ),
    ]
