# Generated by Django 2.0 on 2018-08-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImgViewer', '0002_auto_20180809_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
