# Generated by Django 2.0 on 2018-08-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImgViewer', '0003_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(height_field=500, upload_to='img', width_field=500),
        ),
    ]
