# Generated by Django 2.0 on 2018-08-12 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImgViewer', '0005_auto_20180809_2135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='MyImage',
        ),
    ]
