# Generated by Django 2.0 on 2018-08-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImgViewer', '0006_auto_20180812_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myimage',
            name='image',
            field=models.ImageField(upload_to='img'),
        ),
    ]
