# Generated by Django 2.0 on 2018-08-12 18:03

import ImgViewer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImgViewer', '0007_auto_20180812_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myimage',
            name='image',
            field=models.ImageField(upload_to='img', validators=[ImgViewer.models.SizeCheck]),
        ),
    ]
